---
title: "Illusionz & Magick"
subtitle: "With flipbookr and xaringan"
author: "BWoodz; August 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      
---


```{r include = F}

library(flipbookr)
library(tidyverse)
library(magick)
library(tidyverse)
library(ggplot2)
library(xaringan)
library(xaringanthemer)
library(sysfonts)
library(showtext)

```

---
##Let's begin with a basic rotate
```{r princess, echo = F}

pic <- image_read("princess.png") %>% 
  image_scale("300")
pic

```

---

`r chunk_reveal("pipeline")`

```{r pipeline, include=F}
pic %>%
  image_rotate(45) %>%
  image_rotate(45) %>%
  image_flip() %>%
  image_flop() %>%
  image_fill("pink", point = "+100+200", fuzz = 20) %>%
  image_crop(pic, "100x200+50")
```


---

```{r, echo = F}

circle <- image_read("circle.png")
waldo <- image_read("waldo.jpg") %>% 
  image_scale("5000")
waldo


```

---

```{r, echo = F}

circle <- image_read("circle.png") %>% 
  image_scale("200")
star <- image_read("star.png") %>% 
  image_scale("200")
waldo <- image_read("waldo.jpg") %>% 
  image_scale("5000")
waldo


```



---

##You can add images on top of others
```{r, echo = F}

image_composite(image_scale(waldo, "x1000"), star, offset = "+180+200")

```

```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}
```
