---
title: "Illusionz & Magick"
subtitle: "With flipbookr and xaringan"
author: "BWoodz; August 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      
---


```{r include = F}

library(flipbookr)
library(tidyverse)
library(magick)
library(tidyverse)
library(ggplot2)
library(xaringan)
library(xaringanthemer)
library(sysfonts)
library(showtext)
xaringanExtra::use_share_again()

```

---


`r chunk_reveal("princess")`

```{r princess, include = F}
image_read("princess.png") %>% 
  image_scale("300") %>% 
  # Let's begin with a basic rotate
  image_rotate(45) %>% 
  # A bit more
  image_rotate(90) %>% 
  # Or just flip it!
  image_flip() %>% 
  # You can also add color!
  image_fill("pink", point = "+100+200", 
             fuzz = 20) %>% 
  # And crop your image 
  image_crop("100x200+50")
```


---

`r chunk_reveal("waldo")`

```{r waldo, include = F}
image_read("circle.png") %>% 
  image_scale("200") ->
circle

image_read("star.png") %>% 
  image_scale("200") ->
star

image_read("waldo.jpg") %>% 
  ##You can add images on top of others
  image_composite(star, 
                  offset = 
                    "+780-25") %>% 
  image_composite(circle, 
                  offset = 
                    "+780-25") %>% 
  # And crop your image 
  image_crop("200x200+780")
```



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}
```
